`define ADDR_WIDTH 4
`define DATA_WIDTH 32
`define CLK_FREQ_HZ 100_000_000
`define REFRESH_RATE_HZ 1000
`define  DEBOUNCE_MS 20

`define COUNTER_MAX = (CLK_FREQ_HZ / (REFRESH_RATE_HZ * 4)) - 1
`define IRQ_COUNTER_MAX = (CLK_FREQ_HZ / 1000) * DEBOUNCE_MS - 1
